#      ______                _   __
#     / ____/   _____  _____/ | / /___
#    / __/ | | / / _ \/ ___/  |/ / __ \
#   / /___ | |/ /  __/ /  / /|  / /_/ /
#  /_____/_|___/\___/_/__/_/ |_/\____/   __        __
#        / __ \/ __/ __/ __ \____  _____/ /_____  / /_
#       / / / / /_/ /_/ /_/ / __ \/ ___/ //_/ _ \/ __/
#      / /_/ / __/ __/ _, _/ /_/ / /__/ ,< /  __/ /_
#      \____/_/ /_/ /_/ |_|\____/\___/_/|_|\___/\__/
#
# EverNoOffRocket, made with ♥ by UnStackss
# UnStackss GitHub: https://github.com/UnStackss
# Visit my e-commerce: https://unstackss.dev
bStats: true

# Messages (Colors and HexRGB Support)
messages:
  PlayerSwapHandItemsEvent: "&cNon puoi mettere razzi nella mano secondaria!"
  PlayerInteractEvent: "&cNon puoi usare i razzi dalla mano secondaria!"
  PlayerMoveEvent: "&cI razzi sono stati rimossi dalla mano secondaria!"